// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/shipment": {
            "post": {
                "description": "Create a new shipment with the input data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipments"
                ],
                "summary": "Create a new shipment",
                "parameters": [
                    {
                        "description": "Create shipment",
                        "name": "shipment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.Shipment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/data.Shipment"
                        }
                    }
                }
            }
        },
        "/shipments": {
            "get": {
                "description": "returns array of all shipments from database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipments"
                ],
                "summary": "Get details of all shipments",
                "operationId": "get-all-shipments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/data.Shipment"
                            }
                        }
                    }
                }
            }
        },
        "/shipments/{shipmentId}": {
            "get": {
                "description": "Get details of shipment corresponding to inserted id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipments"
                ],
                "summary": "Get details for a given shipmentID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the shipment",
                        "name": "shipmentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/data.Shipment"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "data.Shipment": {
            "type": "object",
            "properties": {
                "RecipientAddress": {
                    "type": "string"
                },
                "RecipientCountryCode": {
                    "type": "string"
                },
                "RecipientEmail": {
                    "type": "string"
                },
                "RecipientName": {
                    "type": "string"
                },
                "SenderAddress": {
                    "type": "string"
                },
                "SenderCountryCode": {
                    "type": "string"
                },
                "SenderEmail": {
                    "type": "string"
                },
                "SenderName": {
                    "type": "string"
                },
                "Weight": {
                    "type": "number"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Sendify Shipment API",
	Description: "API server for Shipments",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
